### ISSUE TITLE
Error occuring only during server reload on page.

### ISSUE THREAD

**Issue by spiros** [timvink/mkdocs-charts-plugin#22]
Hello, 

I've encountered a weird situation where a page with a bar chart plot renders correctly the first time after a fresh server start but when a change triggers a server reload, the following error occurs:

```
ERROR   -  Error building page 'diseases/cancer.md': 'ChartsPlugin' object has no attribute 'homepage'
Traceback (most recent call last):
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs/livereload/__init__.py", line 190, in _build_loop
    func()
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs/commands/build.py", line 235, in _build_page
    output = config.plugins.on_post_page(output, page=page, config=config)
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs/plugins.py", line 586, in on_post_page
    return self.run_event('post_page', output, page=page, config=config)
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs_charts_plugin/plugin.py", line 80, in on_post_page
    return self.add_javascript_variables(output, page, config)
  File "/Users/spiros/miniconda3/envs/diseaseatlas/lib/python3.8/site-packages/mkdocs_charts_plugin/plugin.py", line 105, in add_javascript_variables
    path_to_homepage = self.homepage.url_relative_to(page.file)
AttributeError: 'ChartsPlugin' object has no attribute 'homepage'
ERROR   -  [13:10:42] An error happened during the rebuild. The server will
           appear stuck until build errors are resolved.
```

The code for the plot in question is this - I've checked using multiple online linters and it does appear valid and well-formed.

```
  ```vegalite
  {
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "description": "A bar chart showing the number of research publications per year.",
    "height": 150,
    "width": 520,
    "data": {
      "values": [{"pub_year":2022,"n":99},{"pub_year":2021,"n":133},{"pub_year":2020,"n":147},{"pub_year":2019,"n":116},{"pub_year":2018,"n":143},{"pub_year":2017,"n":168},{"pub_year":2016,"n":187},{"pub_year":2015,"n":220},{"pub_year":2014,"n":215},{"pub_year":2013,"n":117},{"pub_year":2012,"n":19},{"pub_year":2011,"n":1},{"pub_year":2010,"n":1}]
    },
    "mark": "bar",
    "encoding": {
      "x": { "field": "pub_year"},
      "y": { "field": "n", "aggregate": "sum"}
    }
  }
  ```

I am using Python 3.8, mkdocs version 1.5.2, mkdocs-charts-plugin version 0.0.10.

This is my mkdocs config:

```
site_name: Alpha
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.caret
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
extra:
  analytics:
    provider: google
    property: G-

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  
plugins:
  - charts
  - mermaid2

```

Any ideas much appreciated.

**Comment by timvink** [comment]
You're using an outdated version of this plugin. Upgrade with `pip install -U mkdocs-charts-plugin`.

Closing the issue. Please re-open if upgrading didn't work.

**Comment by timvink** [comment]
(and thanks for reporting nonetheless!)

**Comment by spiros** [comment]
thanks ; that fixed the problem !
